spring:
  cloud:
    stream:
      bindings:
        input:
          destination: new-users
          content-type: application/json
          group: departments
      kafka:
        binder:
          broker: 192.168.99.100
          zkNodes: 192.168.99.100