server:
  port: 8501
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: new-users
          content-type: application/json
      kafka:
        binder:
          broker: 192.168.99.100
          zkNodes: 192.168.99.100
          defaultBrokerPort: 2376
          defaultZkPort: 2181
defaultDepartmentId: 1