version: '3.3'
services:
  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - TOPICS=new-users
      - ADVERTISED_HOST=localhost
      - ADVERTISED_PORT=9092