version: '3.3'
services:
  kafka:
    image: wurstmeister/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - TOPICS=new-users
      - ADVERTISED_HOST=192.168.99.100
      - ADVERTISED_PORT=9092