version: '3.3'
services:
  zookeeper:
    image: vikrammurugesan/zookeeper
    network_mode: host
  mesos_master:
    image: mesosphere/mesos-master
    network_mode: host
    environment:
      MESOS_ZK: zk://localhost:2181/mesos
      MESOS_HOSTNAME: localhost
    depends_on:
      - zookeeper

